# EasyPanel Configuration for TriExpert Services
name: triexpert-services
services:
  - name: app
    source:
      type: github
      repo: your-username/triexpert-services
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile
      context: .
    deploy:
      replicas: 1
      env:
        - name: NODE_ENV
          value: production
        - name: VITE_SUPABASE_URL
          value: https://postgres.triexpertservice.com
        - name: VITE_SUPABASE_ANON_KEY
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
        - name: VITE_PROXMOX_HOST
          value: https://your-proxmox-server:8006
        - name: VITE_PROXMOX_USERNAME
          value: root@pam
        - name: VITE_PROXMOX_PASSWORD
          value: your-proxmox-password
        - name: VITE_N8N_WEBHOOK_URL
          value: https://your-n8n-instance.com/webhook
        - name: VITE_N8N_API_KEY
          value: your-n8n-api-key
        - name: VITE_STRIPE_PUBLISHABLE_KEY
          value: pk_test_your-stripe-key
    ports:
      - protocol: http
        host: 80
        container: 80
    domains:
      - name: triexpert.com
        path: /
    healthcheck:
      path: /health
      port: 80
      initial_delay: 30
      interval: 30
      timeout: 10
      retries: 3