# EasyPanel Configuration for TriExpert Services
name: triexpert-services
services:
  - name: app
    source:
      type: github
      repo: your-username/triexpert-services
      branch: main
    build:
      type: dockerfile
      dockerfile: Dockerfile
      context: .
    deploy:
      replicas: 1
      env:
        - name: NODE_ENV
          value: production
        # Variables se configuran en EasyPanel UI
        # No hardcodeadas aquí
    ports:
      - protocol: http
        host: 80
        container: 80
    domains:
      - name: triexpert.com
        path: /
    healthcheck:
      path: /health
      port: 80
      initial_delay: 30
      interval: 30
      timeout: 10
      retries: 3